name: horaire
description: horaire project
publish_to: 'mas aurelien'

version: 1.0.0+2

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  sqflite: ^2.3.0
  path_provider: any
  flutter_spinkit: ^5.2.0
  page_transition: ^2.1.0
  google_fonts: ^6.1.0
  ionicons: ^0.2.2
  simple_animations: ^5.0.2
  date_picker_timeline: ^1.2.5
  flutter_localization: ^0.1.14
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.0.1
  file_picker: ^6.1.1
  theme_provider: ^0.6.0
  flutter_animate: ^4.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
